# This Vagrantfile create 3 VMs with differents IP addresses

CPU = 1
RAM = 1024

Vagrant.configure("2") do |config|
    config.vm.define "lb" do |lb|
        lb.vm.box = "ubuntu/xenial64"
        lb.vm.provider "virtualbox" do |v|
            v.cpus = CPU
            v.memory = RAM
        end
        lb.vm.network "private_network", ip: "10.0.0.10"
    end
    config.vm.define "web1" do |web1|
        web1.vm.box = "ubuntu/xenial64"
        web1.vm.provider "virtualbox" do |v|
            v.cpus = CPU
            v.memory = RAM
        end
        web1.vm.network "private_network", ip: "10.0.0.11"
    end
    config.vm.define "web2" do |web2|
        web2.vm.box = "ubuntu/xenial64"
        web2.vm.provider "virtualbox" do |v|
            v.cpus = CPU
            v.memory = RAM
        end
        web2.vm.network "private_network", ip: "10.0.0.12"
    end
end
