
CPU = 1
RAM = 1024
IP = "192.168.56.50"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "1.0"
  config.vm.hostname = "nginx-server"
  config.vm.network "private_network", ip: IP
  config.vm.synced_folder "./static-website-example", "/var/www/html"
  config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
  end
end
